def createTitle(studentName, file):
	file.write('\\begin{titlepage} \n')
	file.write('\\begin{center} \n')
	file.write('\\large \n')
	file.write('\\textbf {МІНІСТЕРСТВО ОСВІТИ I НАУКИ УКРАЇНИ} \n\n')
	file.write('\\large \n')
	file.write('Національний університет "Львівська політехніка" \n\n')
	file.write('\\begin{figure}[h] \n')
	file.write('\\includegraphics[width=8cm, height=8cm]{lpLogo} \n')
	file.write('\\centering	\n')
	file.write('\\end{figure} \n\n')
	file.write('\\Large \n')
	file.write('\\textbf{Розрахункова робота} \n\n')
	file.write('\\large	\n')
	file.write('\\з дисципліни \n\n')
	file.write('\\large \n')	
	file.write('\\"Теорія алгоритмів" \n\n')
	file.write('\\vfill \n')
	file.write('\\raggedleft \n')
	file.write('\\normalsize \n')
	file.write('Виконав:\\\\ \n')
	file.write('студент групи КН-26\\\\ \n')
	file.write(studentName+"\\\\ \n")
	file.write('Прийняв:\\\\ \n')
	file.write('Керницький А.Б.\\\\ \n\n')
	file.write('\\vspace{30mm} \n')
	file.write('\\centering \n')
	file.write('\\small \n')
	file.write('\\textbf{Львів 2016} \n')
	file.write('\\end{center} \n')
	file.write('\\end{titlepage} \n')
	
def createFile():
	file = open("Rozraha.tex", 'w+')
	file.write('\\documentclass[a4paper,12pt]{article} \n')
	file.write('\\usepackage[utf8]{inputenc} \n')
	file.write('\\usepackage[english,ukrainian]{babel} \n')
	file.write('\\usepackage[T2A]{fontenc} \n')
	file.write('\\usepackage{graphicx} \n')
	file.write('\\usepackage{helvet} \n')
	file.write('\\graphicspath{{images/}} \n')
	file.write('\\usepackage{geometry} \n')
	file.write('\\geometry{ \n')
	file.write('a4paper, \n')
	file.write('total={170mm,257mm}, \n')
	file.write('left=20mm, \n')
	file.write('top=20mm, \n } \n')
	file.write('\\begin{document} \n\n')
	createTitle("Пилипишин", file)
	file.write('\\end{document} \n')
	file.close()

createFile()